feat: add members page sushi yam
asobiya/asobiya-website pull request #35
Opened 2023-07-26 11:22 UTC by sushi-yam

add sushi yam info in members page

2023-07-26 11:56 UTC, shokaji requested changes
`twitter={''}`
アカウント名が抜けていました。
もしアカウント追加したくない場合は、その部分は削除したほうがいいかもしれません。

2023-07-26 12:02 UTC, alecrem commented
> `twitter={''}`

リンクが出てこないので大丈夫です：

https://asobiya-website-git-feature-add-members-page-sushiyam-asobiya.vercel.app/members

削除した方がわかりやすいとも考えられますけど。

2023-07-26 12:10 UTC, alecrem requested changes

2023-07-26 12:10 UTC, alecrem commented on src/pages/members.tsx
> +            bio={'実験大好き人間'}
`skills` をつけない場合はデフォルトの"All sorts of skills"になりますが、初めての人にどんな人がいるかわかりやすいので入力があった方が嬉しいと思います。

ご参考までに今載っているみんなのスキルを貼ります：

- Skills: Meme, Guitar, 散歩, 聞き上手
- Skills: 絵描き, DTM, バイク整備 
- Skills: 替え歌, frontend, web3

https://asobiya-website.vercel.app/members

2023-07-27 03:47 UTC, alecrem commented on src/pages/members.tsx
> -            twitter={''}
すみません！やっぱり`''`がいいです。
入力がないとデフォルトでasobiya-daoになってしまいます。

最初は合っていたのにすみません・・・

2023-07-27 08:38 UTC, shokaji commented on src/pages/members.tsx
> -            twitter={''}
あ、すいません僕が間違っておりました🙇コード削除するとデフォルトの表示出てきてしまうんですね。

2023-07-27 09:02 UTC, alecrem commented on src/pages/members.tsx
> -            twitter={''}
「ない方がわかりやすい」と言ったのは僕ですけど😂

デフォルトをつけたのも僕。お巡りさん、この人です！🙋

2023-07-27 09:10 UTC, shokaji commented on src/pages/members.tsx
> -            twitter={''}
ピーポーピーポー🚓

2023-07-27 09:37 UTC, sushi-yam commented on src/pages/members.tsx
> -            twitter={''}
変更しました。

2023-07-27 09:52 UTC, alecrem approved these changes
LGTM 🚀
あとはresolve conflict「だけ」ですね。

2023-07-27 10:36 UTC, shokaji approved these changes

2023-07-27 10:37 UTC, merged