indexのコンポーネントのパスの../~を@/~に修正
asobiya/asobiya-website pull request #40
Opened 2023-07-26 15:06 UTC by shokaji

2023-07-26 15:15 UTC, shokaji commented
今考えるとやらなくてもよかったのですが、気になって修正しました。。。

2023-07-27 03:55 UTC, alecrem requested changes
indexだけでNavBarのレイアウトが崩れているのは、NavBarがContainerの中に入っているからだと思います。

membersページみたいにContainerの外に出したら統一感が出るでしょうか。

2023-07-27 09:04 UTC, alecrem approved these changes
LGTM! ありがとうございます。このままマージしていいですか？よかったらどうぞ。

2023-07-27 09:11 UTC, shokaji commented
レビューありがとうございます! Mergeいたします。

2023-07-27 09:11 UTC, merged