Heroコンポーネントのロゴの表示が大きかったので修正しました。
asobiya/asobiya-website pull request #66
Opened 2023-08-10 15:07 UTC by shokaji

無難なサイズにしました。

2023-08-18 12:29 UTC, alecrem requested changes
画面が最大のときは何も変わらないように見えますが、画面が少しだけ小さくなるとロゴがはみ出てしまいます。

`backgroundSize`がもともと`{'contain'}`になっていてレスポンシブになっていると思います。大きい方の画面で背景の大きさを制限したいときは、その背景がついているものの幅を指定する際に[Chakraのarray syntax](https://chakra-ui.com/docs/styled-system/responsive-styles#the-array-syntax)を使うのもいいと思います。

例えば幅として3つの要素の配列を渡すと、画面の大きさによって一つ目（モバイル）、二つ目（タブレット）か三つ目（デスクトップ）の要素が適用されます。

また、 #63 と被る変更がありそうなのでそっちのマージ後に確認したいと思います。

2023-08-18 12:30 UTC, alecrem commented
`backgroundSize={['contain', 'contain', 'auto']}`

でもいいのかな？デスクトップの時だけ今のほんちゃんと変わる仕様になるでしょうか。

2023-08-18 16:35 UTC, shokaji commented
レビューありがとうございます！画面サイズによってはみ出すところ盲点でした。
`backgroundSize={['contain', 'contain', 'auto']}`
に修正いたしました。お時間あるとき再レビューよろしくお願いいたします。

2023-08-19 15:47 UTC, alecrem requested changes
やっぱりウインドウの幅を変えていくと、ロゴが入っていない範囲が大きいかもしれません。今のmainにはそういう問題がないと思います。

三つ目の`'auto'`になるときは、SVGが入っている要素が大きすぎるかもしれません。

あと、向こうをマージしたのに`AboutAsobiya.tsx`への変更がどうしてこのブランチにあるか分かりません。このブランチには`Hero`の中のロゴ画像に関する変更だけあればいいと思います。

2023-08-26 16:36 UTC, shokaji commented
mainをこのfeatureブランチにマージしてしまった件すいませんでした💦

1回マージしてしまったブランチをマージ前の状態に戻すのって大変でしょうか？

2024-01-23 18:26 UTC, closed without merging